services:
  filesharingapp:
    image: filesharingapp
    build:
      context: .
      dockerfile: FileSharingApp/FileSharingApp/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./data:/app/data
      - ./uploads:/app/wwwroot/uploads
